name: funding-watcher
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python aggregator.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WB_DEBUG: "1"
          WB_ROWS: "800"              # scan 800 per page
          WB_PAGES: "10"              # scan 8,000 newest rows
          WB_PUB_WINDOW_DAYS: "180"   # 6 months; drop back to 90 later
          WB_MAX_RESULTS: "60"        # or 100 if you want a bigger list
          # Keep / adjust topic filtering:
          WB_REQUIRE_TOPIC_MATCH: "1" # only OGP-relevant
          WB_TOPIC_LIST: "Access to Information|Anti-Corruption|Civic Space|Climate and Environment|Digital Governance|Fiscal Openness|Gender and Inclusion|Justice|Media Freedom|Public Participation"
          # Optional: additional keyword filter (pipe-separated). Start empty; add later if needed:
          WB_QTERM: ""
      - name: Persist state
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "funding-watcher-bot"
          git add state.json || true
          git commit -m "update state $(date -u +'%F %T')" || echo "no changes"
          git push || echo "no push (likely no changes)"
