name: funding-watcher
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python aggregator.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WB_DEBUG: "1"
          WB_ROWS: "200"               # can go up to 1000
          WB_PAGES: "10"               # scan up to 2000 items
          WB_PUB_WINDOW_DAYS: "90"     # your rule; try 180 while validating
          WB_MAX_RESULTS: "40"
          # Optional client-side filter. Start empty while validating:
          # WB_QTERM: 'request for bids|request for expressions of interest|eoi|rfp'
      - name: Persist state
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "funding-watcher-bot"
          git add state.json || true
          git commit -m "update state $(date -u +'%F %T')" || echo "no changes"
          git push || echo "no push (likely no changes)"
